//! RISC Zero script for GCP Confidential Space attestation proof generation
//!
//! This script reads attestation samples and generates ZK proofs that can be
//! verified on-chain.

use alloy::{
    primitives::{keccak256, Address},
    sol_types::SolValue,
};
use clap::Parser;
use gcp_attestation::{extract_kid_from_jwt, verify_attestation, JwkKey};
use gcp_cs_attestation_risc0_program::PublicValuesStruct;
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts};
use serde::Deserialize;
use std::fs;

// Include the compiled RISC Zero guest program ELF and image ID
// These are generated by risc0-build during compilation
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

#[derive(Parser, Debug)]
#[command(author, version, about = "GCP Confidential Space attestation prover (RISC Zero)")]
struct Args {
    /// Execute the program (test mode, no proof)
    #[arg(long)]
    execute: bool,

    /// Generate a ZK proof
    #[arg(long)]
    prove: bool,

    /// Path to the attestation sample JSON file
    #[arg(long, default_value = "../../samples/samples_1764707758.json")]
    sample: String,

    /// Which sample index to use (0-based)
    #[arg(long, default_value = "0")]
    index: usize,
}

/// Attestation bundle from the sample capture workload
#[derive(Debug, Deserialize)]
struct AttestationBundle {
    samples: Vec<AttestationSample>,
    jwks: Jwks,
}

#[derive(Debug, Deserialize)]
struct AttestationSample {
    raw_token: String,
    audience: String,
}

#[derive(Debug, Deserialize)]
struct Jwks {
    keys: Vec<JwkKey>,
}

fn main() {
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::EnvFilter::from_default_env())
        .init();

    let args = Args::parse();

    if args.execute == args.prove {
        eprintln!("Error: You must specify either --execute or --prove");
        std::process::exit(1);
    }

    // Load the attestation sample
    println!("Loading sample from: {}", args.sample);
    let content = fs::read_to_string(&args.sample).expect("Failed to read sample file");
    let bundle: AttestationBundle =
        serde_json::from_str(&content).expect("Failed to parse sample JSON");

    if args.index >= bundle.samples.len() {
        eprintln!(
            "Error: Sample index {} out of range (have {} samples)",
            args.index,
            bundle.samples.len()
        );
        std::process::exit(1);
    }

    let sample = &bundle.samples[args.index];
    println!(
        "Using sample {} with audience: {}",
        args.index, sample.audience
    );

    // Find the JWK for this token (extract kid from JWT header)
    let kid =
        extract_kid_from_jwt(sample.raw_token.as_bytes()).expect("Failed to extract kid from JWT");
    println!("Token signed with key ID: {}", kid);

    let jwk = bundle
        .jwks
        .keys
        .iter()
        .find(|k| k.kid == kid)
        .expect("JWK not found for token's key ID")
        .clone();

    // Generate a mock EVM public key for testing (64 bytes)
    // In production, this would be the sequencer/validator's secp256k1 public key
    let mock_evm_public_key: [u8; 64] = {
        let mut key = [0u8; 64];
        // Use a deterministic pattern for reproducible tests
        for (i, byte) in key.iter_mut().enumerate() {
            *byte = (i as u8).wrapping_mul(7).wrapping_add(42);
        }
        key
    };

    // Derive expected address from mock EVM public key
    let pubkey_hash = keccak256(&mock_evm_public_key);
    let expected_evm_address = Address::from_slice(&pubkey_hash[12..]);
    println!("Mock EVM address: {}", expected_evm_address);

    // Generate mock image signature for testing (65 bytes: r || s || v)
    // In production, this would come from CI signing the container image digest with secp256k1
    let mock_image_signature: [u8; 65] = {
        let mut sig = [0u8; 65];
        // r (32 bytes)
        for (i, byte) in sig[0..32].iter_mut().enumerate() {
            *byte = (i as u8).wrapping_mul(11).wrapping_add(17);
        }
        // s (32 bytes)
        for (i, byte) in sig[32..64].iter_mut().enumerate() {
            *byte = (i as u8).wrapping_mul(13).wrapping_add(23);
        }
        // v (1 byte) - valid recovery id
        sig[64] = 27;
        sig
    };

    // Build executor environment with inputs
    let env = ExecutorEnv::builder()
        .write(&sample.raw_token.as_bytes().to_vec())
        .expect("Failed to write JWT token")
        .write(&jwk)
        .expect("Failed to write JWK")
        .write(&sample.audience.to_string())
        .expect("Failed to write audience")
        .write(&mock_evm_public_key.to_vec())
        .expect("Failed to write EVM public key")
        .write(&mock_image_signature.to_vec())
        .expect("Failed to write image signature")
        .build()
        .expect("Failed to build executor environment");

    if args.execute {
        println!("\n=== Executing program (test mode) ===\n");

        let prover = default_prover();
        let prove_info = prover
            .prove_with_opts(env, GCP_CS_ATTESTATION_RISC0_PROGRAM_ELF, &ProverOpts::fast())
            .expect("Execution failed");

        let receipt = prove_info.receipt;
        let output = receipt.journal.bytes.clone();

        println!("Program executed successfully!");

        // Decode the public values
        let public_values = PublicValuesStruct::abi_decode_validate(output.as_slice())
            .expect("Failed to decode output");

        println!("\n=== Public Values ===");
        println!(
            "jwk_key_hash: 0x{}",
            hex::encode(public_values.jwk_key_hash)
        );
        println!(
            "validity_window_start: {}",
            public_values.validity_window_start
        );
        println!("validity_window_end: {}", public_values.validity_window_end);
        println!(
            "image_digest_hash: 0x{}",
            hex::encode(public_values.image_digest_hash)
        );
        println!("tee_signing_key: {}", public_values.tee_signing_key);
        println!("secboot: {}", public_values.secboot);
        println!("dbgstat_disabled: {}", public_values.dbgstat_disabled);
        println!(
            "audience_hash: 0x{}",
            hex::encode(public_values.audience_hash)
        );
        println!("image_signature_v: {}", public_values.image_signature_v);
        println!(
            "image_signature_r: 0x{}",
            hex::encode(public_values.image_signature_r)
        );
        println!(
            "image_signature_s: 0x{}",
            hex::encode(public_values.image_signature_s)
        );

        // Verify against local verification
        let expected = verify_attestation(
            sample.raw_token.as_bytes(),
            &jwk,
            Some(&sample.audience),
            None,
        )
        .expect("Local verification failed");

        assert_eq!(
            public_values.jwk_key_hash,
            keccak256(expected.signing_key_id.as_bytes())
        );
        assert_eq!(
            public_values.validity_window_start,
            expected.validity_window_start
        );
        assert_eq!(
            public_values.validity_window_end,
            expected.validity_window_end
        );
        assert_eq!(
            public_values.image_digest_hash,
            keccak256(expected.image_digest.as_bytes())
        );
        assert_eq!(public_values.secboot, expected.secboot);
        assert_eq!(
            public_values.audience_hash,
            keccak256(expected.audience.as_bytes())
        );
        assert_eq!(
            public_values.tee_signing_key, expected_evm_address,
            "EVM address mismatch"
        );

        println!("\nAll values match local verification!");

        // Print image ID for contract configuration
        println!("\n=== RISC Zero Image ID ===");
        let mut image_id_bytes = [0u8; 32];
        for (i, word) in GCP_CS_ATTESTATION_RISC0_PROGRAM_ID.iter().enumerate() {
            image_id_bytes[i * 4..(i + 1) * 4].copy_from_slice(&word.to_le_bytes());
        }
        println!("Image ID (bytes32): 0x{}", hex::encode(image_id_bytes));
    } else {
        println!("\n=== Generating Groth16 ZK proof ===\n");

        let prover = default_prover();
        let prove_info = prover
            .prove_with_opts(
                env,
                GCP_CS_ATTESTATION_RISC0_PROGRAM_ELF,
                &ProverOpts::groth16(),
            )
            .expect("Proof generation failed");

        let receipt = prove_info.receipt;

        println!("Proof generated successfully!");

        // Verify the proof
        receipt
            .verify(GCP_CS_ATTESTATION_RISC0_PROGRAM_ID)
            .expect("Proof verification failed");
        println!("Proof verified successfully!");

        // Print proof details
        let journal = receipt.journal.bytes.clone();
        let seal = receipt
            .inner
            .groth16()
            .expect("Failed to get Groth16 proof")
            .seal
            .clone();

        println!("\n=== Proof Output ===");
        println!("Journal (public values): {} bytes", journal.len());
        println!("Seal (proof): {} bytes", seal.len());

        // Print image ID for contract configuration
        println!("\n=== RISC Zero Image ID ===");
        let mut image_id_bytes = [0u8; 32];
        for (i, word) in GCP_CS_ATTESTATION_RISC0_PROGRAM_ID.iter().enumerate() {
            image_id_bytes[i * 4..(i + 1) * 4].copy_from_slice(&word.to_le_bytes());
        }
        println!("Image ID (bytes32): 0x{}", hex::encode(image_id_bytes));
    }
}
