//! RISC Zero proof generation wrapper

use alloy::sol_types::SolValue;
use anyhow::{Context, Result};
use gcp_attestation::{extract_kid_from_jwt, JwkKey};
use gcp_cs_attestation_risc0_program::PublicValuesStruct;
use risc0_ethereum_contracts::encode_seal;
use risc0_zkvm::{default_prover, ExecutorEnv, ProverOpts};
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{debug, info};

// Include the compiled RISC Zero guest program ELF and image ID
// These are generated by risc0-build during compilation
// Allow dead_code for unused generated constants (e.g., *_PATH)
#[allow(dead_code)]
mod methods {
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));
}
use methods::{GCP_CS_ATTESTATION_RISC0_PROGRAM_ELF, GCP_CS_ATTESTATION_RISC0_PROGRAM_ID};

/// Get the RISC Zero image ID as bytes32 for Solidity contracts.
/// This is a standalone function that reads compile-time constants only.
pub fn risc0_image_id_bytes32() -> [u8; 32] {
    let mut bytes = [0u8; 32];
    for (i, word) in GCP_CS_ATTESTATION_RISC0_PROGRAM_ID.iter().enumerate() {
        bytes[i * 4..(i + 1) * 4].copy_from_slice(&word.to_le_bytes());
    }
    bytes
}

/// Output from proof generation
pub struct ProofOutput {
    /// ABI-encoded public values (journal)
    pub public_values: Vec<u8>,
    /// Groth16 proof bytes (seal)
    pub proof_bytes: Vec<u8>,
}

/// Wrapper around RISC Zero prover for attestation proofs
pub struct AttestationProver;

impl AttestationProver {
    /// Create a new prover using local GPU (CUDA) or CPU proving
    ///
    /// RISC Zero supports native GPU proving that works directly on Cloud Run with L4 GPUs.
    pub fn new() -> Self {
        info!("Initializing RISC Zero prover (local GPU/CPU)");
        Self
    }

    /// Generate a proof for the given attestation token
    ///
    /// # Arguments
    /// * `jwt_token` - Raw JWT attestation token from Confidential Space
    /// * `jwk` - JWK public key that signed the token
    /// * `expected_audience` - Expected audience claim
    /// * `evm_public_key` - 64-byte uncompressed secp256k1 public key for EVM signing
    /// * `image_signature` - 65-byte secp256k1 signature (r || s || v) over keccak256(image_digest)
    ///
    /// # Returns
    /// The proof output with public values and proof bytes
    pub fn generate_proof(
        &self,
        jwt_token: &str,
        jwk: &JwkKey,
        expected_audience: &str,
        evm_public_key: &[u8; 64],
        image_signature: &[u8],
    ) -> Result<ProofOutput> {
        info!("Starting RISC Zero proof generation");

        // Build executor environment with inputs
        let env = ExecutorEnv::builder()
            .write(&jwt_token.as_bytes().to_vec())
            .context("Failed to write JWT token")?
            .write(jwk)
            .context("Failed to write JWK")?
            .write(&expected_audience.to_string())
            .context("Failed to write audience")?
            .write(&evm_public_key.to_vec())
            .context("Failed to write EVM public key")?
            .write(&image_signature.to_vec())
            .context("Failed to write image signature")?
            .build()
            .context("Failed to build executor environment")?;

        // Generate Groth16 proof for on-chain verification
        // Uses GPU if available (cuda feature), otherwise falls back to CPU
        info!("Generating Groth16 ZK proof (this may take several minutes)");
        let prover = default_prover();
        let prove_info = prover
            .prove_with_opts(env, GCP_CS_ATTESTATION_RISC0_PROGRAM_ELF, &ProverOpts::groth16())
            .context("RISC Zero proof generation failed")?;

        let receipt = prove_info.receipt;

        // Verify the proof locally before returning
        debug!("Verifying proof locally");
        receipt
            .verify(GCP_CS_ATTESTATION_RISC0_PROGRAM_ID)
            .context("Local proof verification failed")?;

        info!("Proof generated and verified successfully");

        // Extract journal (public values) and seal (proof bytes)
        let journal = receipt.journal.bytes.clone();

        // Encode the seal for on-chain verification
        // This prepends the 4-byte verifier selector derived from Groth16 vkey and control IDs
        // The selector is required by RiscZeroVerifierRouter to route to the correct verifier
        let seal = encode_seal(&receipt)
            .context("Failed to encode seal for on-chain verification")?;

        Ok(ProofOutput {
            public_values: journal,
            proof_bytes: seal,
        })
    }

    /// Get the image ID as bytes32 for Solidity contracts
    pub fn image_id_bytes32(&self) -> [u8; 32] {
        risc0_image_id_bytes32()
    }
}

/// JWKS cache for fetching Google's public keys
pub struct JwksCache {
    keys: Arc<RwLock<Option<CachedJwks>>>,
    discovery_url: String,
    cache_ttl_secs: u64,
    client: reqwest::Client,
}

struct CachedJwks {
    keys: Vec<JwkKey>,
    fetched_at: std::time::Instant,
}

#[derive(serde::Deserialize)]
struct OidcDiscovery {
    jwks_uri: String,
}

#[derive(serde::Deserialize)]
struct JwksResponse {
    keys: Vec<JwkKey>,
}

/// Default timeout for JWKS HTTP requests (30 seconds)
const JWKS_HTTP_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(30);

impl JwksCache {
    /// Create a new JWKS cache
    pub fn new(discovery_url: String, cache_ttl_secs: u64) -> Self {
        let client = reqwest::Client::builder()
            .timeout(JWKS_HTTP_TIMEOUT)
            .build()
            .expect("Failed to build HTTP client for JWKS cache");

        Self {
            keys: Arc::new(RwLock::new(None)),
            discovery_url,
            cache_ttl_secs,
            client,
        }
    }

    /// Get the JWK for a given key ID
    pub async fn get_jwk(&self, kid: &str) -> Result<JwkKey> {
        let keys = self.get_keys().await?;
        keys.into_iter()
            .find(|k| k.kid == kid)
            .ok_or_else(|| anyhow::anyhow!("JWK not found for kid: {}", kid))
    }

    /// Get all cached keys, refreshing if needed
    async fn get_keys(&self) -> Result<Vec<JwkKey>> {
        // Check cache
        {
            let cache = self.keys.read().await;
            if let Some(ref cached) = *cache {
                if cached.fetched_at.elapsed().as_secs() < self.cache_ttl_secs {
                    debug!("Using cached JWKS");
                    return Ok(cached.keys.clone());
                }
            }
        }

        // Fetch fresh JWKS
        info!("Fetching fresh JWKS from Google");

        // Get JWKS URI from discovery document
        let discovery: OidcDiscovery = self
            .client
            .get(&self.discovery_url)
            .send()
            .await
            .context("Failed to fetch OIDC discovery document")?
            .json()
            .await
            .context("Failed to parse OIDC discovery document")?;

        // Fetch JWKS
        let jwks: JwksResponse = self
            .client
            .get(&discovery.jwks_uri)
            .send()
            .await
            .context("Failed to fetch JWKS")?
            .json()
            .await
            .context("Failed to parse JWKS")?;

        info!(count = jwks.keys.len(), "Fetched JWKS keys");

        // Update cache
        let keys = jwks.keys.clone();
        {
            let mut cache = self.keys.write().await;
            *cache = Some(CachedJwks {
                keys: jwks.keys,
                fetched_at: std::time::Instant::now(),
            });
        }

        Ok(keys)
    }
}

/// Extract the key ID from a JWT token
pub fn get_jwt_kid(jwt_token: &str) -> Result<String> {
    extract_kid_from_jwt(jwt_token.as_bytes())
        .map_err(|e| anyhow::anyhow!("Failed to extract kid from JWT: {:?}", e))
}

/// Decode public values from proof journal
pub fn decode_public_values(output: &[u8]) -> Result<PublicValuesStruct> {
    PublicValuesStruct::abi_decode_validate(output)
        .map_err(|e| anyhow::anyhow!("Failed to decode public values: {:?}", e))
}

#[cfg(test)]
mod tests {
    use super::*;
    use alloy::primitives::keccak256;
    use gcp_attestation::verify_attestation;
    use risc0_zkvm::ProverOpts;
    use serde::Deserialize;

    /// Attestation bundle from sample capture workload
    #[derive(Debug, Deserialize)]
    struct AttestationBundle {
        samples: Vec<AttestationSample>,
        jwks: Jwks,
    }

    #[derive(Debug, Deserialize)]
    struct AttestationSample {
        raw_token: String,
        audience: String,
    }

    #[derive(Debug, Deserialize)]
    struct Jwks {
        keys: Vec<JwkKey>,
    }

    /// Test guest program execution with all sample attestation data files.
    ///
    /// This test validates that the guest program correctly:
    /// 1. Parses and verifies JWT attestation tokens
    /// 2. Extracts claims from the token
    /// 3. Produces correct public values for on-chain verification
    ///
    /// Automatically tests all samples_*.json files in test-data/.
    ///
    /// Run locally with: `cargo test -p proof-service --release`
    /// Note: Requires RISC Zero toolchain installed.
    #[test]
    fn test_guest_execution_with_sample_attestations() {
        let test_data_dir = concat!(env!("CARGO_MANIFEST_DIR"), "/test-data");

        // Find all sample files
        let sample_files: Vec<_> = std::fs::read_dir(test_data_dir)
            .expect("Failed to read test-data directory")
            .filter_map(|entry| {
                let entry = entry.ok()?;
                let path = entry.path();
                if path.extension()?.to_str()? == "json"
                    && path.file_name()?.to_str()?.starts_with("samples_")
                {
                    Some(path)
                } else {
                    None
                }
            })
            .collect();

        assert!(
            !sample_files.is_empty(),
            "No sample files found in test-data/"
        );

        println!("Found {} sample file(s)", sample_files.len());

        for sample_path in sample_files {
            println!("Testing: {}", sample_path.display());

            let content = std::fs::read_to_string(&sample_path)
                .unwrap_or_else(|e| panic!("Failed to read {}: {}", sample_path.display(), e));
            let bundle: AttestationBundle = serde_json::from_str(&content)
                .unwrap_or_else(|e| panic!("Failed to parse {}: {}", sample_path.display(), e));

            // Test each sample in the bundle
            for (i, sample) in bundle.samples.iter().enumerate() {
                println!("  Sample {}: audience={}", i, sample.audience);
                run_guest_execution_test(sample, &bundle.jwks.keys);
            }
        }
    }

    /// Run guest execution test for a single sample
    fn run_guest_execution_test(sample: &AttestationSample, jwks: &[JwkKey]) {
        // Find the JWK for this token
        let kid = extract_kid_from_jwt(sample.raw_token.as_bytes())
            .expect("Failed to extract kid from JWT");
        let jwk = jwks
            .iter()
            .find(|k| k.kid == kid)
            .expect("JWK not found for token's key ID")
            .clone();

        // Generate mock EVM public key (64 bytes) - deterministic for reproducible tests
        let mock_evm_public_key: [u8; 64] = {
            let mut key = [0u8; 64];
            for (i, byte) in key.iter_mut().enumerate() {
                *byte = (i as u8).wrapping_mul(7).wrapping_add(42);
            }
            key
        };

        // Generate mock image signature (65 bytes: r || s || v)
        let mock_image_signature: [u8; 65] = {
            let mut sig = [0u8; 65];
            for (i, byte) in sig[0..32].iter_mut().enumerate() {
                *byte = (i as u8).wrapping_mul(11).wrapping_add(17);
            }
            for (i, byte) in sig[32..64].iter_mut().enumerate() {
                *byte = (i as u8).wrapping_mul(13).wrapping_add(23);
            }
            sig[64] = 27; // valid recovery id
            sig
        };

        // Build executor environment
        let env = ExecutorEnv::builder()
            .write(&sample.raw_token.as_bytes().to_vec())
            .expect("Failed to write JWT token")
            .write(&jwk)
            .expect("Failed to write JWK")
            .write(&sample.audience.to_string())
            .expect("Failed to write audience")
            .write(&mock_evm_public_key.to_vec())
            .expect("Failed to write EVM public key")
            .write(&mock_image_signature.to_vec())
            .expect("Failed to write image signature")
            .build()
            .expect("Failed to build executor environment");

        // Run in execute mode (fast, no proof generation)
        let prover = default_prover();
        let prove_info = prover
            .prove_with_opts(env, GCP_CS_ATTESTATION_RISC0_PROGRAM_ELF, &ProverOpts::fast())
            .expect("Guest execution failed");

        let receipt = prove_info.receipt;
        let output = receipt.journal.bytes.clone();

        // Decode and verify public values
        let public_values = PublicValuesStruct::abi_decode_validate(output.as_slice())
            .expect("Failed to decode output");

        // Verify against local attestation verification
        let expected = verify_attestation(
            sample.raw_token.as_bytes(),
            &jwk,
            Some(&sample.audience),
            None,
        )
        .expect("Local verification failed");

        assert_eq!(
            public_values.jwk_key_hash,
            keccak256(expected.signing_key_id.as_bytes()),
            "JWK key hash mismatch"
        );
        assert_eq!(
            public_values.validity_window_start, expected.validity_window_start,
            "Validity window start mismatch"
        );
        assert_eq!(
            public_values.validity_window_end, expected.validity_window_end,
            "Validity window end mismatch"
        );
        assert_eq!(
            public_values.image_digest_hash,
            keccak256(expected.image_digest.as_bytes()),
            "Image digest hash mismatch"
        );
        assert_eq!(public_values.secboot, expected.secboot, "Secboot mismatch");
    }
}
