//! RISC Zero proof generation wrapper

use alloy::sol_types::SolValue;
use anyhow::{Context, Result};
use gcp_attestation::{extract_kid_from_jwt, JwkKey};
use gcp_cs_attestation_risc0_program::PublicValuesStruct;
use risc0_zkvm::{default_prover, sha::Digestible, ExecutorEnv, ProverOpts, Receipt};
use std::sync::Arc;
use tokio::sync::RwLock;
use tracing::{debug, info};

// Include the compiled RISC Zero guest program ELF and image ID
// These are generated by risc0-build during compilation
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

/// Output from proof generation
pub struct ProofOutput {
    /// ABI-encoded public values (journal)
    pub public_values: Vec<u8>,
    /// Groth16 proof bytes (seal)
    pub proof_bytes: Vec<u8>,
}

/// Wrapper around RISC Zero prover for attestation proofs
pub struct AttestationProver;

impl AttestationProver {
    /// Create a new prover using local GPU (CUDA) or CPU proving
    ///
    /// Unlike SP1 which requires network proving, RISC Zero supports native GPU proving
    /// that works directly on Cloud Run with L4 GPUs.
    pub fn new() -> Self {
        info!("Initializing RISC Zero prover (local GPU/CPU)");
        Self
    }

    /// Generate a proof for the given attestation token
    ///
    /// # Arguments
    /// * `jwt_token` - Raw JWT attestation token from Confidential Space
    /// * `jwk` - JWK public key that signed the token
    /// * `expected_audience` - Expected audience claim
    /// * `evm_public_key` - 64-byte uncompressed secp256k1 public key for EVM signing
    /// * `image_signature` - 65-byte secp256k1 signature (r || s || v) over keccak256(image_digest)
    ///
    /// # Returns
    /// The proof output with public values and proof bytes
    pub fn generate_proof(
        &self,
        jwt_token: &str,
        jwk: &JwkKey,
        expected_audience: &str,
        evm_public_key: &[u8; 64],
        image_signature: &[u8],
    ) -> Result<ProofOutput> {
        info!("Starting RISC Zero proof generation");

        // Build executor environment with inputs (same order as SP1)
        let env = ExecutorEnv::builder()
            .write(&jwt_token.as_bytes().to_vec())
            .context("Failed to write JWT token")?
            .write(jwk)
            .context("Failed to write JWK")?
            .write(&expected_audience.to_string())
            .context("Failed to write audience")?
            .write(&evm_public_key.to_vec())
            .context("Failed to write EVM public key")?
            .write(&image_signature.to_vec())
            .context("Failed to write image signature")?
            .build()
            .context("Failed to build executor environment")?;

        // Generate Groth16 proof for on-chain verification
        // Uses GPU if available (cuda feature), otherwise falls back to CPU
        info!("Generating Groth16 ZK proof (this may take several minutes)");
        let prover = default_prover();
        let prove_info = prover
            .prove_with_opts(env, GCP_CS_ATTESTATION_RISC0_PROGRAM_ELF, &ProverOpts::groth16())
            .context("RISC Zero proof generation failed")?;

        let receipt = prove_info.receipt;

        // Verify the proof locally before returning
        debug!("Verifying proof locally");
        receipt
            .verify(GCP_CS_ATTESTATION_RISC0_PROGRAM_ID)
            .context("Local proof verification failed")?;

        info!("Proof generated and verified successfully");

        // Extract journal (public values) and seal (proof bytes)
        let journal = receipt.journal.bytes.clone();

        // Get the Groth16 seal for on-chain verification
        let seal = receipt
            .inner
            .groth16()
            .context("Failed to get Groth16 proof - receipt may not be Groth16 format")?
            .seal
            .clone();

        Ok(ProofOutput {
            public_values: journal,
            proof_bytes: seal,
        })
    }

    /// Get the RISC Zero image ID for this program
    ///
    /// This is needed for on-chain verification to identify which program produced the proof.
    pub fn image_id(&self) -> [u32; 8] {
        GCP_CS_ATTESTATION_RISC0_PROGRAM_ID
    }

    /// Get the image ID as bytes32 for Solidity contracts
    pub fn image_id_bytes32(&self) -> [u8; 32] {
        let mut bytes = [0u8; 32];
        for (i, word) in GCP_CS_ATTESTATION_RISC0_PROGRAM_ID.iter().enumerate() {
            bytes[i * 4..(i + 1) * 4].copy_from_slice(&word.to_le_bytes());
        }
        bytes
    }
}

/// JWKS cache for fetching Google's public keys
pub struct JwksCache {
    keys: Arc<RwLock<Option<CachedJwks>>>,
    discovery_url: String,
    cache_ttl_secs: u64,
    client: reqwest::Client,
}

struct CachedJwks {
    keys: Vec<JwkKey>,
    fetched_at: std::time::Instant,
}

#[derive(serde::Deserialize)]
struct OidcDiscovery {
    jwks_uri: String,
}

#[derive(serde::Deserialize)]
struct JwksResponse {
    keys: Vec<JwkKey>,
}

/// Default timeout for JWKS HTTP requests (30 seconds)
const JWKS_HTTP_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(30);

impl JwksCache {
    /// Create a new JWKS cache
    pub fn new(discovery_url: String, cache_ttl_secs: u64) -> Self {
        let client = reqwest::Client::builder()
            .timeout(JWKS_HTTP_TIMEOUT)
            .build()
            .expect("Failed to build HTTP client for JWKS cache");

        Self {
            keys: Arc::new(RwLock::new(None)),
            discovery_url,
            cache_ttl_secs,
            client,
        }
    }

    /// Get the JWK for a given key ID
    pub async fn get_jwk(&self, kid: &str) -> Result<JwkKey> {
        let keys = self.get_keys().await?;
        keys.into_iter()
            .find(|k| k.kid == kid)
            .ok_or_else(|| anyhow::anyhow!("JWK not found for kid: {}", kid))
    }

    /// Get all cached keys, refreshing if needed
    async fn get_keys(&self) -> Result<Vec<JwkKey>> {
        // Check cache
        {
            let cache = self.keys.read().await;
            if let Some(ref cached) = *cache {
                if cached.fetched_at.elapsed().as_secs() < self.cache_ttl_secs {
                    debug!("Using cached JWKS");
                    return Ok(cached.keys.clone());
                }
            }
        }

        // Fetch fresh JWKS
        info!("Fetching fresh JWKS from Google");

        // Get JWKS URI from discovery document
        let discovery: OidcDiscovery = self
            .client
            .get(&self.discovery_url)
            .send()
            .await
            .context("Failed to fetch OIDC discovery document")?
            .json()
            .await
            .context("Failed to parse OIDC discovery document")?;

        // Fetch JWKS
        let jwks: JwksResponse = self
            .client
            .get(&discovery.jwks_uri)
            .send()
            .await
            .context("Failed to fetch JWKS")?
            .json()
            .await
            .context("Failed to parse JWKS")?;

        info!(count = jwks.keys.len(), "Fetched JWKS keys");

        // Update cache
        let keys = jwks.keys.clone();
        {
            let mut cache = self.keys.write().await;
            *cache = Some(CachedJwks {
                keys: jwks.keys,
                fetched_at: std::time::Instant::now(),
            });
        }

        Ok(keys)
    }
}

/// Extract the key ID from a JWT token
pub fn get_jwt_kid(jwt_token: &str) -> Result<String> {
    extract_kid_from_jwt(jwt_token.as_bytes())
        .map_err(|e| anyhow::anyhow!("Failed to extract kid from JWT: {:?}", e))
}

/// Decode public values from proof journal
pub fn decode_public_values(output: &[u8]) -> Result<PublicValuesStruct> {
    PublicValuesStruct::abi_decode_validate(output)
        .map_err(|e| anyhow::anyhow!("Failed to decode public values: {:?}", e))
}
